ManagementSystem/ManagementSystem/urls.py
from app import views, admin, account, user
from django.urls import path, include

urlpatterns = [
    # 通用部分
    # 注册
    path('register/', account.register, name="register"),  # 管理员账号无法注册
    # 登录
    path('login/', account.login, name="login"),
    # 登录忘记密码
    # path('forgotPwd/', account.forgot_Pwd, name="forgotPwd"),    # 管理员账号的密码无法修改，只能联系更高层的管理者
    # 图片验证码
    path("image/code/", account.image_code),
    # 注销
    path('logout/', account.logout),

    # 管理员模式
    # 主页面
    path('admin/list/', admin.admin_list),
    # 增删改查
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    # 重置
    path('admin/<int:nid>/reset/', admin.admin_reset),
    # # 管理员管理的用户表
    path('user/list/', user.user_list, name='user_list'),
    # path('admin/user/add/', admin.admin_user_add),
    # path('admin/user/<int:nid>/delete/', admin.admin_user_delete),
    # path('admin/user/<int:nid>/reset/', admin.admin_plate_reset),
    # # 管理员管理的车牌信息表
    # path('admin/plate/', admin.admin_plate),
    # path('admin/plate/add/', admin.admin_plate_add),
    # path('admin/plate/<int:nid>/reset/', admin.admin_plate_reset),
    # path('admin/plate/<int:nid>/delete/', admin.admin_plate_delete),
    # 进出时间表
    path('admin/time/', admin.admin_time),
    path('admin/<int:nid>/time/', admin.admin_time_delete),
    path('admin/<int:nid>/pay/', admin.admin_pay_delete),

    path('user/time/', user.user_time),
    # 车牌识别
    path('video/', views.video, name="video"),
    path('get/txt/', views.get_txt),
    path('show/video/', views.show_video),

    path('video_out/', views.video_out, name="out"),
    path('get/out/', views.get_out),
    path('show/out/', views.show_out),

    path('admin/pay/list/', admin.admin_pay_list),
    path('user/pay/list/', user.user_pay_list),

    path('user/<int:nid>/pay/', user.user_pay),
    path('user/pay/notify/', user.user_pay_notify),
    path('processData/', user.process_data, name='process_data'),
]

ManagementSystem/app/models.py
import uuid
from datetime import datetime

from django.db import models

from django.utils import timezone

timezone.now()


# python manage.py makemigrations
# python manage.py migrate


class Vehicle(models.Model):
    LicensePlate = models.CharField(verbose_name="车牌号", max_length=20)
    Name = models.CharField(verbose_name="姓名", max_length=20)
    phone = models.CharField(verbose_name="电话", max_length=20)
    VehicleColor = models.CharField(verbose_name="车牌颜色", max_length=20)

    def __str__(self):
        return self.LicensePlate


class User(models.Model):
    phone = models.CharField(verbose_name="电话", max_length=32)
    Account = models.CharField(verbose_name="账号", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=128)
    gender_choices = (
        (1, "男"),
        (2, "女"),
        (3, "保密"),
    )
    Sex = models.SmallIntegerField(verbose_name="性别", choices=gender_choices, default=1)


class Admin(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)
    gender_choices = (
        (1, "男"),
        (2, "女"),
        (3, "保密"),
    )
    sex = models.SmallIntegerField(verbose_name="性别", choices=gender_choices, default=1)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    admin_choices = (
        (0, "否"),
        (1, "是"),
    )

    admin = models.SmallIntegerField(verbose_name="是否为管理员", choices=admin_choices, default=0)


class Plate(models.Model):
    LicensePlate = models.CharField(verbose_name="车牌号", max_length=30)
    created_in = models.DateTimeField(auto_now_add=True, verbose_name="进入时间")

    created_out = models.DateTimeField(auto_now_add=False, verbose_name="外出时间", null=True, blank=True)
    user = models.ForeignKey(Admin, on_delete=models.SET_NULL, verbose_name="用户", null=True)


class Order(models.Model):
    order_number = models.CharField(verbose_name="订单号", max_length=30)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    time = models.DateTimeField(auto_now_add=True, verbose_name="支付时间")
    plate = models.ForeignKey(Plate, on_delete=models.SET_NULL, null=True, verbose_name="车牌号")

    status_choices = (
        (0, "否"),
        (1, "是"),
    )

    status = models.SmallIntegerField(verbose_name="是否已支付", choices=status_choices, default=0)



# CREATE TABLE vehicle (
#     id INT AUTO_INCREMENT PRIMARY KEY,
#     LicensePlate VARCHAR(20) NOT NULL,
#     Name VARCHAR(20) NOT NULL,
#     phone VARCHAR(20) NOT NULL,
#     VehicleColor VARCHAR(20) NOT NULL
# );
#
# CREATE TABLE user (
#     id INT AUTO_INCREMENT PRIMARY KEY,
#     phone VARCHAR(32) NOT NULL,
#     Account VARCHAR(32) NOT NULL,
#     password VARCHAR(128) NOT NULL,
#     Sex SMALLINT NOT NULL DEFAULT 1
# );
#
# CREATE TABLE datetimefield (
#     id INT AUTO_INCREMENT PRIMARY KEY,
#     LicensePlate VARCHAR(30) NOT NULL,
#     created_in DATETIME DEFAULT CURRENT_TIMESTAMP,
#     created_out DATETIME DEFAULT CURRENT_TIMESTAMP
# );
#
# CREATE TABLE admin (
#     id INT AUTO_INCREMENT PRIMARY KEY,
#     username VARCHAR(32) NOT NULL,
#     password VARCHAR(32) NOT NULL
# );

ManagementSystem/app/templates/admin_edit.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
    <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">编辑</h3>
  </div>


  <form method="post" novalidate>
    {% csrf_token %}


     {% for field in form %}

        <div class="form-group">
            <label >
                 {{field.label}}
            </label>
                   {{ field }}
            <span style="color: red;">{{field.errors.0}}</span>
       </div>

    {% endfor %}


      <button type="submit" class="btn btn-primary">保存</button>
</form>

</div>
  </div>

{% endblock %}

ManagementSystem/app/templates/admin_list.html
{% extends "list.html" %}

 {% block head %}
  <ul class="nav navbar-nav">
        <li><a href="/admin/list/">用户信息</a></li>
        <li><a href="/admin/time/">行车记录</a></li>
        <li><a href="/show/video/">实时监控</a></li>
        <li><a href="/admin/pay/list/">支付信息</a></li>
  </ul>
{% endblock %}

{% block js %}
    function confirmDelete(id) {
      var result = confirm("确定要删除吗？");
      if (result) {
        // 用户点击了确认按钮，跳转到删除链接
        window.location.href = "/admin/" + id + "/delete/";
      } else {
        // 用户点击了取消按钮，不执行跳转操作
      }
    }

{% endblock %}




{% block create %}
      <a href="/admin/add/" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
        新建
      </a>

{% endblock %}

{% block thead %}
          <tr>
              <th>ID</th>
              <th>账号</th>
              <th>密码</th>
              <th>性别</th>
              <th>创建时间</th>
              <th>管理员</th>
              <th>操作</th>
          </tr>
{% endblock %}


{% block tbody %}

        {% for obj in queryset %}
          <tr>
              <td>{{ obj.id }}</td>
              <td>{{ obj.username }}</td>
<!--              <td>{{ obj.password }}</td>-->
              <td>**********</td>
              <td>{{ obj.get_sex_display }}</td>
              <td>{{ obj.created_time }}</td>
              <td>{{ obj.get_admin_display }}</td>

              <td>
                  <a href="/admin/{{ obj.id }}/edit/"  class="btn btn-primary btn-xs" >编辑</a>
                    <button  onclick="confirmDelete({{ obj.id }})" class="btn btn-danger btn-xs">删除</button>
<!--                  <a href="/admin/{{ obj.id }}/delete/" class="btn btn-danger btn-xs">删除</a>-->
              </td>
          </tr>
        {% endfor %}

{% endblock %}

ManagementSystem/app/templates/admin_order.html
{% extends "list.html" %}

 {% block head %}

  <ul class="nav navbar-nav">
        <li><a href="/admin/list/">用户信息</a></li>
        <li><a href="/admin/time/">行车记录</a></li>
        <li><a href="/show/video/">实时监控</a></li>
        <li><a href="/admin/pay/list/">支付信息</a></li>


  </ul>

{% endblock %}


{% block js %}

function redirectToAlipay(id) {

window.open('/user/' + id + '/pay/');
}
{% endblock %}
{% block thead %}
          <tr>
              <th>ID</th>
              <th>订单号</th>
              <th>金额</th>
              <td>用户</td>
              <th>车牌号</th>
              <th>创建时间</th>
              <th>是否已支付</th>

<!--              <th>操作</th>-->
          </tr>

{% endblock %}

{% block tbody %}

        {% for obj in queryset %}
          <tr>
              <td>{{ obj.id }}</td>
              <td>{{ obj.order_number }}</td>
              <td>{{ obj.amount }}</td>
              <td>{{ obj.plate.user.username }}</td>
              <td>{{ obj.plate.LicensePlate}}</td>
              <td>{{ obj.time }}</td>
              <td>{{ obj.get_status_display }}

<!--              <td>-->
<!--              <button onclick="redirectToAlipay({{ obj.id }})" class="btn btn-primary btn-xs">支付</button>-->
<!--            </td>-->
          </tr>
        {% endfor %}

{% endblock %}

ManagementSystem/app/templates/admin_plate.html
{% extends "list.html" %}

 {% block head %}

  <ul class="nav navbar-nav">
        <li><a href="/admin/list/">用户信息</a></li>
        <li><a href="/admin/time/">行车记录</a></li>
        <li><a href="/show/video/">实时监控</a></li>
        <li><a href="/admin/pay/list/">支付信息</a></li>


  </ul>

{% endblock %}

{% block js %}
    function confirmDelete(id) {
      var result = confirm("确定要删除吗？");
      if (result) {
        // 用户点击了确认按钮，跳转到删除链接
        window.location.href = "/admin/" + id + "/time/";
      } else {
        // 用户点击了取消按钮，不执行跳转操作
      }
    }

{% endblock %}


{% block thead %}
          <tr>
              <th>ID</th>
              <th>车牌号</th>
              <th>进入时间</th>
              <th>离开时间</th>
              <th>用户</th>
              <th>操作</th>

          </tr>

{% endblock %}


{% block tbody %}

        {% for obj in queryset %}
          <tr>
              <td>{{ obj.id }}</td>
              <th>{{ obj.LicensePlate }}</th>
              <td>{{ obj.created_in }}</td>
              <td>{{ obj.created_out }}</td>
              <td>{{ obj.user.username }}</td>
              <td>
<!--                  <a href="/admin/{{obj.id}}/time/"  class="btn btn-danger btn-xs">删除</a>-->
                  <button  onclick="confirmDelete({{ obj.id }})" class="btn btn-danger btn-xs">删除</button>
            </td>
          </tr>
        {% endfor %}

{% endblock %}

ManagementSystem/app/templates/change.html
{% extends "layout.html" %}
{% block admin %}

  <ul class="nav navbar-nav">
        <li><a href="/admin/list/">用户信息</a></li>
        <li><a href="/admin/time/">行车记录</a></li>
        <li><a href="/show/video/">实时监控</a></li>
        <li><a href="/admin/pay/list/">支付信息</a></li>

  </ul>

{% endblock %}
{% block content %}
<div class="container">
    <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">{{title}}</h3>
  </div>


  <form method="post" novalidate>
    {% csrf_token %}


     {% for field in form %}

        <div class="form-group">
            <label >
                 {{field.label}}
            </label>
                   {{ field }}
            <span style="color: red;">{{field.errors.0}}</span>
       </div>

    {% endfor %}


      <button type="submit" class="btn btn-primary">保存</button>
</form>

</div>
  </div>

{% endblock %}

ManagementSystem/app/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>车辆管理系统</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}">
  <style>
    .navbar{
      border-radius:0;
    }
  </style>
  <script >
            {% block script %}{% endblock %}
  </script>


</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">车辆管理系统</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      {% block admin %}{% endblock %}


      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"
             role="button" aria-haspopup="true" aria-expanded="false">
            {{request.session.info.name}}
            <span class="caret"></span></a>

          <ul class="dropdown-menu">
            <li role="separator" class="divider"></li>
            <li><a href="/logout/">注销</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div>
      {% block content %}{% endblock %}

</div>
{% block video %}{% endblock %}


<script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
</body>
</html>

ManagementSystem/app/templates/list.html
{% extends "layout.html" %}

{% block script %}
{% block js %}{% endblock %}
{% endblock %}


{% block admin %}

 {% block head %}{% endblock %}

{% endblock %}

{% block content %}

  <div class="container">

    <div style="margin-bottom: 10px" class="clearfix">
        {% block create %}{% endblock %}
<!--        <div style="float: right;width: 600px;">-->
<!--            <div class="col-lg-6">-->
<!--                <form method="get">-->
<!--                    <div class="input-group">-->
<!--                        <input type="text" name="q" class="form-control" placeholder="搜索" value="{{search_data}}">-->
<!--                        <span class="input-group-btn">-->
<!--                    <button class="btn btn-default" type="submit">搜索</button>-->
<!--                  </span>-->
<!--                    </div>-->
<!--                </form>-->
<!--            </div>-->

<!--        </div>-->
        
    </div>

<div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
        列表
      </div>


      <!-- Table -->
      <table class="table table-bordered" >
        <thead>
        {% block thead %}{% endblock %}
        </thead>
        <tbody>
        {% block tbody %}{% endblock %}
        </tbody>
      </table>
    </div>
        <nav aria-label="...">
              <ul class="pagination">
               {{page_string}}
             </ul>
           </nav>
{% endblock %}

ManagementSystem/app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}">

    <style>
        .account{
        width:500px;
        border: 1px solid #dddddd;
        border-radius:5px;
        box-shadow:5px 5px 5px #aaa;
        height:400px;
        margin-left:auto;
        margin-right:auto;
        margin-top:200px;
        padding:20px 40px;

        }
        .account h1{
        text-align:center;
        }
    </style>
</head>
<body>
<div class="account">
    <h1>用户登录</h1>
    <form method="post" novalidate>
        {% csrf_token %}
  <div class="form-group">
    <label >用户名</label>
    {{ form.username }}
      <span style="color:red;">{{form.username.errors.0}}</span>
  </div>
  <div class="form-group">
    <label >密码</label>
    {{ form.password }}
        <span style="color:red;">{{form.password.errors.0}}</span>
  </div>
        <div class="form-group">
            <label >图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color:red;">{{form.code.errors.0}}</span>
                </div>
                <div class="col-xs-5">
                    <img src="/image/code/" alt="Example Image">
<!--                    <img src="image/code/" id="image_code" alt="">-->
                </div>
            </div>
        </div>
    <button type="submit" class="btn btn-primary">登录</button>
        <a href="/register/">注册</a>
<!--        <a href="/forgotPwd/">忘记密码</a>-->


</form>

</div>
<script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
</body>
</html>

ManagementSystem/app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}">
        <style>
        .account{
        width:500px;
        border: 1px solid #dddddd;
        border-radius:5px;
        box-shadow:5px 5px 5px #aaa;
        height:250px;
        margin-left:auto;
        margin-right:auto;
        margin-top:200px;
        padding:20px 40px;

        }
        .account h1{
        text-align:center;
        }
    </style>
</head>

<body>
<div class="account">
  <form method="post" novalidate>
    {% csrf_token %}


     {% for field in form %}

        <div class="form-group">
            <label >
                 {{field.label}}
            </label>
                   {{ field }}
            <span style="color: red;">{{field.errors.0}}</span>
       </div>

    {% endfor %}


      <button type="submit" class="btn btn-primary">保存</button>
</div>
</form>
</body>
</html>

ManagementSystem/app/templates/show_video.html
{% extends "layout.html" %}
{% block admin %}

  <ul class="nav navbar-nav">
        <li><a href="/admin/list/">用户信息</a></li>
        <li><a href="/admin/time/">行车记录</a></li>
        <li><a href="/show/video/">实时监控</a></li>
        <li><a href="/admin/pay/list/">支付信息</a></li>


  </ul>

{% endblock %}

{% block script %}
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>

setInterval(function() {
    $.ajax({
        url: "/get/txt/",
        type: "GET",
        dataType: "json",
        success: function(data) {
            // 清空 #message 元素的内容
            $("#message1").empty();

            $.each(data, function(key, value) {
                var tag = $("<div>").text(value);
                $("#message1").append(tag);
                console.log("请求发送成功", value);
            });
        },
        error: function(xhr, status, error) {
            console.log("请求发送失败", error);
        }
    });
}, 5000);

setInterval(function() {
    $.ajax({
        url: "/get/out/",
        type: "GET",
        dataType: "json",
        success: function(data) {
            // 清空 #message 元素的内容
            $("#message2").empty();

            $.each(data, function(key, value) {
                var tag = $("<div>").text(value);
                $("#message2").append(tag);
                console.log("请求发送成功", value);
            });
        },
        error: function(xhr, status, error) {
            console.log("请求发送失败", error);
        }
    });
}, 5000);


</script>

<style>
.box1 {
    text-align: center;
    background-color: red;
    border-radius: 20px;
    width: 800px;
    height: 640px;
    position: absolute;
    left: 5%;
    top: 45%;
    transform: translate(0, -50%);
}
.box2 {

	text-align: center;
	background-color: red;
	border-radius: 20px;
	width: 800px;
	height: 640px;
	position: absolute;
	left: 50%;
	top: 45%;
	transform: translate(0,-50%);
}
</style>


{% endblock %}

{% block video %}
<div class="box1">
            <img  src="{% url 'video' %}" alt="无信号源">
        <ul>
            {% for frame in data_dict.data_list %}
                <li>{{ frame }}</li>
            {% endfor %}
        </ul>
         <h1>入口</h1>
        <div id="message1"></div>
</div>

<div class="box2">
            <img  src="{% url 'out' %}" alt="无信号源">
        <ul>
            {% for frame in data_dict.frame_list %}
                <li>{{ frame }}</li>
            {% endfor %}
        </ul>
         <h1>出口</h1>
        <div id="message2"></div>
</div>

{% endblock %}

ManagementSystem/app/templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

     <h1>用户注册</h1>
     <form method="post" action="">
         {% csrf_token %}


         <input type="text" name="Name" placeholder="昵称">
         <input type="text" name="Account" placeholder="账户">
         <input type="password" name="password" placeholder="密码">
         <div>
             <label>性别</label>
             <select >
                 {% for item in gender_choices %}
                 <option value="{{item.0}}">{{item.1}}</option>
                 {% endfor %}
             </select>
         </div>
         <input type="submit" value="提交">
         <span style="color: red">{{error_msg}}</span>

     </form>

</body>
</html>

ManagementSystem/app/templates/user_list.html
{% extends "list.html" %}

 {% block head %}

  <ul class="nav navbar-nav">
        <li><a href="/user/list/">用户信息</a></li>
        <li><a href="/user/time/">行车记录</a></li>
        <li><a href="/user/pay/list/">支付信息</a></li>
  </ul>

{% endblock %}


{% block thead %}
          <tr>
              <th>ID</th>
              <th>账号</th>
              <th>密码</th>
              <th>性别</th>
              <th>创建时间</th>
              <th>操作</th>
          </tr>

{% endblock %}
{% block js %}

{% endblock %}

{% block create %}
<form method="POST" action="{% url 'process_data' %}">
  {% csrf_token %}
    <h3>绑定车牌号</h3>
  <input type="text" name="data">
  <button type="submit">提交</button>
</form>
{% endblock %}
{% block tbody %}

        {% for obj in queryset %}
          <tr>
              <td>{{ obj.id }}</td>
              <td>{{ obj.username }}</td>
              <td>{{ obj.password }}</td>
<!--              <td>**********</td>-->
              <td>{{ obj.get_sex_display }}</td>
              <td>{{ obj.created_time }}</td>
              <td>
                  <a href="/admin/{{ obj.id }}/edit/"  class="btn btn-primary btn-xs" >编辑</a>
            </td>
          </tr>
        {% endfor %}



{% endblock %}

ManagementSystem/app/templates/user_order.html
{% extends "list.html" %}

 {% block head %}

  <ul class="nav navbar-nav">
        <li><a href="/user/list/">用户信息</a></li>
        <li><a href="/user/time/">行车记录</a></li>
        <li><a href="/user/pay/list/">支付信息</a></li>

  </ul>

{% endblock %}

{% block js %}

function redirectToAlipay(id) {

window.open('/user/' + id + '/pay/');
}

{% endblock %}

{% block thead %}
          <tr>
              <th>ID</th>
              <th>订单号</th>
              <th>金额</th>
              <th>创建时间</th>
              <th>是否已支付</th>
              <th>操作</th>
          </tr>

{% endblock %}

{% block tbody %}

        {% for obj in queryset %}

          <tr>
              <td>{{ obj.id }}</td>
              <td>{{ obj.order_number }}</td>
              <td>{{ obj.amount }}</td>
              <td>{{ obj.time }}</td>
              <td>{{ obj.get_status_display }}
              <td>
              <button onclick="redirectToAlipay({{ obj.id }})" class="btn btn-primary btn-xs">支付</button>
            </td>
          </tr>
        {% endfor %}

{% endblock %}

ManagementSystem/app/templates/user_plate.html
{% extends "list.html" %}

 {% block head %}

  <ul class="nav navbar-nav">
        <li><a href="/user/list/">用户信息</a></li>
        <li><a href="/user/time/">行车记录</a></li>
        <li><a href="/user/pay/list/">支付信息</a></li>
  </ul>

{% endblock %}


{% block thead %}
          <tr>
              <th>ID</th>
              <th>车牌号</th>
              <th>进入时间</th>
              <th>离开时间</th>
          </tr>

{% endblock %}


{% block tbody %}

        {% for obj in queryset %}
          <tr>
              <td>{{ obj.id }}</td>
              <th>{{ obj.LicensePlate }}</th>
              <td>{{ obj.created_in }}</td>
              <td>{{ obj.created_out }}</td>
          </tr>
        {% endfor %}

{% endblock %}